version: "3.8"

services:
    frontend:
        ports:
            - ${FRONTEND_PORT_EXTERNAL}:${FRONTEND_PORT}
        depends_on:
            - backend
            - database
        networks:
            - slack-cut-n-nasty
        environment:
            - APP_NAME=${APP_NAME}
            - BACKEND_URL=${BACKEND_URL}
            - FRONTEND_PORT=${FRONTEND_PORT}
            - NODE_ENV=${NODE_ENV}
    backend:
        ports:
            - ${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT}
        depends_on:
            - database
        networks:
            - slack-cut-n-nasty
        environment:
            - APP_NAME=${APP_NAME}
            - BACKEND_PORT=${BACKEND_PORT}
            - FRONTEND_URL=${FRONTEND_URL}
            - NODE_ENV=${NODE_ENV}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_PORT=${POSTGRES_PORT}
            - POSTGRES_USER=${POSTGRES_USER}
    database:
        image: postgres:13.3-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT}
        volumes:
            - database-data:${POSTGRES_DATA}
        networks:
            - slack-cut-n-nasty
        environment:
            - POSTGRES_DATA=${POSTGRES_DATA}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_HOST=${POSTGRES_HOST}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}

networks:
    slack-cut-n-nasty:
        driver: bridge

volumes:
    database-data:
        driver: local
