version: "3.8"

services:
    frontend:
        restart: always
        ports:
            - ${FRONTEND_PORT_EXTERNAL}:${FRONTEND_PORT}
        depends_on:
            - backend
            - database
        networks:
            - slack-cut-n-nasty
        environment:
            - API_PREFIX
            - APP_NAME
            - BACKEND_PORT
            - BACKEND_PORT_EXTERNAL
            - BACKEND_HOST
            - FRONTEND_HOST
            - FRONTEND_PORT
            - FRONTEND_PORT_EXTERNAL
            - NODE_ENV
    backend:
        restart: always
        ports:
            - ${BACKEND_PORT_EXTERNAL}:${BACKEND_PORT}
        depends_on:
            - database
        networks:
            - slack-cut-n-nasty
        environment:
            - API_PREFIX
            - APP_NAME
            - BACKEND_HOST
            - BACKEND_PORT
            - BACKEND_PORT_DEBUG
            - BACKEND_PORT_EXTERNAL
            - FRONTEND_PORT_EXTERNAL
            - GOOGLE_CLIENT_ID
            - GOOGLE_CLIENT_SECRET
            - GOOGLE_REDIRECT_PATH
            - JWT_EXPIRES_IN
            - JWT_SECRET
            - NODE_ENV
            - POSTGRES_DB
            - POSTGRES_HOST
            - POSTGRES_PASSWORD
            - POSTGRES_PORT
            - POSTGRES_USER
    database:
        container_name: slack-cut-n-nasty_database
        image: postgres:13.3-alpine
        restart: always
        ports:
            - ${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT}
        volumes:
            - database-data:${POSTGRES_DATA}
        networks:
            - slack-cut-n-nasty
        environment:
            - POSTGRES_DATA
            - POSTGRES_DB
            - POSTGRES_HOST
            - POSTGRES_PASSWORD
            - POSTGRES_USER

networks:
    slack-cut-n-nasty:
        driver: bridge

volumes:
    database-data:
        driver: local
