version: "3.8"

services:
    frontend:
        container_name: slack-cut-n-nasty_dev_frontend
        build:
            context: ./frontend
            dockerfile: ./build/Dockerfile.development
        command: npm start
        volumes:
            - ./frontend:/app
    backend:
        container_name: slack-cut-n-nasty_dev_backend
        build:
            context: ./backend
            dockerfile: ./build/Dockerfile.development
        volumes:
            - ./backend:/app
        command: npm run start:dev
    database:
        container_name: slack-cut-n-nasty_dev_database
