version: "3.8"

services:
    backend:
        container_name: slack-cut-n-nasty_dev_backend
        build:
            context: ./backend
            dockerfile: ./build/Dockerfile.development
        volumes:
            - ./backend:/app
        command: npm run start:dev
