version: "3.8"

services:
    frontend:
        container_name: slack-cut-n-nasty_dev_frontend
        build:
            context: ./frontend
            dockerfile: ./builder/Dockerfile.development
        command: npm start
        tty: true
        volumes:
            - ./frontend:/app
            # - /app/node_modules
    backend:
        container_name: slack-cut-n-nasty_dev_backend
        ports:
            - ${BACKEND_PORT_DEBUG}:${BACKEND_PORT_DEBUG}
        build:
            context: ./backend
            dockerfile: ./builder/Dockerfile.development
        volumes:
            - ./backend:/app
            # - /app/node_modules
        command: npm run start:debug
